ALTER TABLE [dbo].[APPLICATION_VERSION]
    ADD CONSTRAINT [FK_APPLICATION_VERSION_APPLICATIONS] FOREIGN KEY ([APV_APP_ID]) REFERENCES [dbo].[APPLICATIONS] ([APP_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

