ALTER TABLE [dbo].[APPLICATION_VERSION]
    ADD CONSTRAINT [PK_APPLICATION_VERSION] PRIMARY KEY CLUSTERED ([APV_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

