ALTER TABLE [dbo].[APPLICATIONS]
    ADD CONSTRAINT [UK_APP_NAME] UNIQUE NONCLUSTERED ([APP_NAME] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

