ALTER TABLE [dbo].[LOG_TYPE]
    ADD CONSTRAINT [UK_LTY_CODE] UNIQUE NONCLUSTERED ([LTY_CODE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

