<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true"
    CodeBehind="NewUser.aspx.cs" Inherits="WebSite.administration.NewUser" %>

<%@ MasterType VirtualPath="~/MasterPage.Master" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:ScriptManagerProxy ID="ScriptManagerProxy1" runat="server">
        <Scripts>
            <asp:ScriptReference Path="~/Scripts/postback.js" />
        </Scripts>
    </asp:ScriptManagerProxy>

    <asp:Label runat="server" Text="Login: " />
    <asp:TextBox ID="tbxLogin" runat="server" MaxLength="20" /><br />
    <asp:RequiredFieldValidator ID="reqLogin" runat="server" ControlToValidate="tbxLogin" Text="You must provide a login." Display="Dynamic" />
    <asp:CustomValidator ID="vldLogin" runat="server" Text="Login already used." OnServerValidate="vldLogin_ServerValidate" Display="Dynamic"/><br />

    <asp:Label runat="server" Text="Mail: " />
    <asp:TextBox ID="tbxMail" runat="server" MaxLength="50" /><br />
    <asp:RequiredFieldValidator runat="server" ControlToValidate="tbxMail" Text="You must provide a mail." Display="Dynamic" />
    <asp:CustomValidator ID="csvMail" runat="server" Text="Mail already used." OnServerValidate="csvMail_ServerValidate" Display="Dynamic" /><br />

    <asp:Label runat="server" Text="Password: " />
    <asp:TextBox ID="tbxPassword" runat="server" MaxLength="20" /><br />
    <asp:RequiredFieldValidator runat="server" ControlToValidate="tbxPassword" Text="You must provide a password." Display="Dynamic" /><br />

    <asp:Label runat="server" Text='<%= "Choose user allowed rights." %>' />
    <asp:TreeView ID="trvRights" runat="server" OnInit="trvRights_Init" PopulateNodesFromClient="False" ShowCheckBoxes="All" OnTreeNodeDataBound="trvRights_TreeNodeDataBound" AutoGenerateDataBindings="false"
        OnTreeNodeCheckChanged="trvRights_TreeNodeCheckChanged" ShowLines="True" onclick="javascript:postBackByObject(event);">
        <DataBindings>
            <asp:TreeNodeBinding DataMember="System.Data.DataRowView" TextField="RIG_LABEL" ValueField="RIG_ID"
                SelectAction="None" />
        </DataBindings>
    </asp:TreeView><br />

    <asp:Button ID="btnValider" runat="server" Text="Validate" OnClick="btnValider_Click" />
</asp:Content>
