<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true"
    CodeBehind="UserRights.aspx.cs" Inherits="WebSite.administration.UserRights" %>

<%@ MasterType VirtualPath="~/MasterPage.Master" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:ScriptManagerProxy ID="ScriptManagerProxy1" runat="server">
        <Scripts>
            <asp:ScriptReference Path="~/Scripts/postback.js" />
        </Scripts>
    </asp:ScriptManagerProxy>

    <asp:Label runat="server" Text='<%= "Choose " + CurrentUser.Login + " allowed rights." %>' />

    <asp:TreeView ID="trvRights" runat="server" OnInit="trvRights_Init" PopulateNodesFromClient="False"
        ShowCheckBoxes="All" OnTreeNodeDataBound="trvRights_TreeNodeDataBound" AutoGenerateDataBindings="false"
        OnTreeNodeCheckChanged="trvRights_TreeNodeCheckChanged" ShowLines="True" onclick="javascript:postBackByObject(event);">
        <DataBindings>
            <asp:TreeNodeBinding DataMember="System.Data.DataRowView" TextField="RIG_LABEL" ValueField="RIG_ID"
                SelectAction="None" />
        </DataBindings>
    </asp:TreeView>
    <asp:Button ID="btnValider" runat="server" Text="Validate" 
        onclick="btnValider_Click" />
</asp:Content>
