CREATE PROCEDURE [dbo].[GET_USER_RIGHTS]
	@USR_ID int = null
AS
	IF @USR_ID IS NOT NULL
	BEGIN
		SELECT RIG_ID, RIG_PARENT_ID, RIG_LABEL, CASE WHEN RUR_RIG_ID IS NULL THEN 0 ELSE 1 END AS RIG_SELECTED
		FROM [RIGHT]
		LEFT OUTER JOIN REL_USER_RIGHT ON RIG_ID = RUR_RIG_ID
		WHERE ISNULL(RUR_USR_ID,@USR_ID) = @USR_ID
	END
	ELSE
		SELECT RIG_ID, RIG_PARENT_ID, RIG_LABEL, 0 AS RIG_SELECTED
		FROM [RIGHT]