CREATE TABLE [dbo].[RIGHT]
(
	RIG_ID int IDENTITY(1,1) NOT NULL, 
	RIG_PARENT_ID int NULL,
	RIG_CODE nvarchar(5) NOT NULL,
	RIG_LABEL nvarchar(30) NOT NULL,
	RIG_CREATION_DATE datetime NOT NULL DEFAULT(getdate()),
	RIG_CREATION_USER int NOT NULL,
	RIG_LAST_MODIFICATION_DATE datetime NOT NULL DEFAULT(getdate()),
	RIG_LAST_MODIFICATION_USER int NOT NULL,
	RIG_STATUT bit NOT NULL default(1)
)
