CREATE TABLE [dbo].[ROLE]
(
	ROL_ID int IDENTITY(1,1) NOT NULL, 
	ROL_CODE nvarchar(5) NOT NULL,
	ROL_LABEL nvarchar(30) NOT NULL,
	ROL_CREATION_DATE datetime NOT NULL DEFAULT(getdate()),
	ROL_CREATION_USER int NOT NULL,
	ROL_LAST_MODIFICATION_DATE datetime NOT NULL DEFAULT(getdate()),
	ROL_LAST_MODIFICATION_USER int NOT NULL,
	ROL_STATUT bit NOT NULL default(1)
)
