CREATE TABLE [dbo].[USER]
(
	USR_ID int IDENTITY(1,1) NOT NULL, 
	USR_LOGIN nvarchar(20) NOT NULL,
	USR_PASSWORD nvarchar(20) NOT NULL,
	USR_MAIL nvarchar(50) NOT NULL,
	USR_CREATION_DATE datetime NOT NULL DEFAULT(getdate()),
	USR_CREATION_USER int NOT NULL,
	USR_LAST_MODIFICATION_DATE datetime NOT NULL DEFAULT(getdate()),
	USR_LAST_MODIFICATION_USER int NOT NULL,
	USR_STATUT bit NOT NULL default(1)
)
